class OfficeBearerListModel {
  OfficeBearerListModel({
    required this.memberName,
    required this.memberType,
    required this.mobile,
    required this.status,
    required this.designationName,
    required this.id,
    required this.bearerType,
    required this.stateId,
    required this.districtId,
    required this.constituencyId,
    required this.panchayathId,
    required this.wardId,
    required this.unitId,
    required this.memberId,
    required this.designationId,
    required this.educationQualification,
    required this.job,
    required this.otherJob,
    required this.interestedArea,
    required this.otherInterestedArea,
    required this.martialArts,
    required this.languages,
    required this.facebook,
    required this.selfWrite,
    required this.instagram,
    required this.instagramActive,
    required this.twitter,
    required this.twitterActive,
    required this.speech,
    required this.studyClass,
    required this.writePoemStory,
    required this.slogan,
    required this.serviceAttitude,
    required this.councelling,
    required this.personalRelationship,
    required this.newChances,
    required this.organization,
    required this.teamWork,
    required this.inspireTeammates,
    required this.otherLanguage,
  });

  String memberName;
  String memberType;
  String mobile;
  String status;
  String designationName;
  String id;
  String bearerType;
  String stateId;
  String districtId;
  String constituencyId;
  String panchayathId;
  String wardId;
  String unitId;
  String memberId;
  String designationId;
  dynamic educationQualification;
  dynamic job;
  dynamic otherJob;
  dynamic interestedArea;
  dynamic otherInterestedArea;
  dynamic martialArts;
  dynamic languages;
  dynamic facebook;
  dynamic selfWrite;
  dynamic instagram;
  dynamic instagramActive;
  dynamic twitter;
  dynamic twitterActive;
  dynamic speech;
  dynamic studyClass;
  dynamic writePoemStory;
  dynamic slogan;
  dynamic serviceAttitude;
  dynamic councelling;
  dynamic personalRelationship;
  dynamic newChances;
  dynamic organization;
  dynamic teamWork;
  dynamic inspireTeammates;
  dynamic otherLanguage;

  factory OfficeBearerListModel.fromJson(Map<String, dynamic> json) =>
      OfficeBearerListModel(
        memberName: json["member_name"].toString(),
        memberType: json["member_type"].toString(),
        mobile: json["mobile"].toString(),
        status: json["status"],
        designationName: json["designation_name"],
        id: json["id"],
        bearerType: json["bearer_type"],
        stateId: json["state_id"],
        districtId: json["district_id"],
        constituencyId: json["constituency_id"],
        panchayathId: json["panchayath_id"],
        wardId: json["ward_id"],
        unitId: json["unit_id"],
        memberId: json["member_id"],
        designationId: json["designation_id"],
        educationQualification: json["education_qualification"],
        job: json["job"],
        otherJob: json["other_job"],
        interestedArea: json["interested_area"] != null
            ? json["interested_area"].split(",")
            : [],
        otherInterestedArea: json["other_interested_area"],
        martialArts: json["martial_arts"],
        languages:
            json["languages"] != null ? json["languages"].split(",") : [],
        facebook: json["facebook"],
        selfWrite: json["self_write"],
        instagram: json["instagram"],
        instagramActive: json["instagram_active"],
        twitter: json["twitter"],
        twitterActive: json["twitter_active"],
        speech: json["speech"],
        studyClass: json["study_class"],
        writePoemStory: json["write_poem_story"],
        slogan: json["slogan"],
        serviceAttitude: json["service_attitude"],
        councelling: json["councelling"],
        personalRelationship: json["personal_relationship"],
        newChances: json["new_chances"],
        organization: json["organization"],
        teamWork: json["team_work"],
        inspireTeammates: json["inspire_teammates"],
        otherLanguage: json["other_language"],
      );
}
